# Generated by Django 4.1.1 on 2023-01-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuedonar',
            name='count',
            field=models.CharField(max_length=2, verbose_name='cost'),
        ),
    ]
