# Generated by Django 4.1.1 on 2023-01-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_sale', '0005_menuedonar_date_sale_alter_menuedonar_menue_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuedonar',
            name='date_sale',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
    ]
